//! Build step: type-strip the TypeScript front-end.
//!
//! The editor UI lives in `web/src/*.ts`. There is no Node toolchain in the
//! shipped build — instead this script parses each module with the oxc
//! toolchain (a Rust crate), strips the TypeScript type annotations, and writes
//! plain ES modules to `$OUT_DIR/web/`. A generated `web_modules.rs` table maps
//! each served path (`state.js`, `main.js`, …) to its embedded source; the
//! server includes that table (see `src/serve/assets.rs`) and serves the
//! modules under `/src/<name>.js`. The browser loads them as native ES modules,
//! so no bundler/minifier is involved — the transform is type-strip only and
//! keeps the `import`/`export` graph intact.
//!
//! `tsc` (the type checker) is a CI-only gate; it never runs here or in a
//! release build.

use std::fs;
use std::path::{Path, PathBuf};

use oxc_allocator::Allocator;
use oxc_codegen::Codegen;
use oxc_parser::Parser;
use oxc_semantic::SemanticBuilder;
use oxc_span::SourceType;
use oxc_transformer::{TransformOptions, Transformer};
use serde_json::{json, Map, Value};

fn main() {
    compile_windows_resources();

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest.join("web/src");
    let styles_dir = manifest.join("web/styles");
    let themes_path = manifest.join("web/themes.json");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let web_out = out_dir.join("web");

    // Rebuild whenever a source module (or this script) changes. The directory
    // watch catches added/removed files; per-file watches catch edits.
    println!("cargo:rerun-if-changed=build.rs");
    // `cli::update` reads this with `option_env!` to embed the Ed25519 key that
    // release signatures are checked against (#191). Cargo does not track
    // `option_env!` inputs on its own, so rotating the key would otherwise
    // reuse a stale build.
    println!("cargo:rerun-if-env-changed=AYAME_UPDATE_PUBKEY");
    check_update_pubkey();
    println!("cargo:rerun-if-changed=web/src");
    println!("cargo:rerun-if-changed=web/styles");
    println!("cargo:rerun-if-changed={}", themes_path.display());

    let themes_source = fs::read_to_string(&themes_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", themes_path.display()));
    let themes: Value = serde_json::from_str(&themes_source)
        .unwrap_or_else(|e| panic!("parse {}: {e}", themes_path.display()));
    validate_themes(&themes);
    let theme_module = generate_theme_module(&themes);
    fs::create_dir_all(&web_out).unwrap();
    fs::write(web_out.join("style.css"), concatenate_styles(&styles_dir)).unwrap();
    fs::write(web_out.join("themes.css"), generate_themes_css(&themes)).unwrap();

    let mut ts_files = Vec::new();
    collect_ts(&src_dir, &mut ts_files);
    ts_files.sort();
    assert!(
        !ts_files.is_empty(),
        "no .ts modules found under {}",
        src_dir.display()
    );

    let mut entries: Vec<String> = Vec::new();
    for path in &ts_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path.strip_prefix(&src_dir).unwrap();
        let rel_js = rel.with_extension("js");
        let rel_js_str = rel_js.to_string_lossy().replace('\\', "/");
        let js = if rel == Path::new("theme-presets.ts") {
            theme_module.clone()
        } else {
            let source =
                fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            transform_ts(path, &source)
        };
        let dest = web_out.join(&rel_js);
        fs::create_dir_all(dest.parent().unwrap()).unwrap();
        fs::write(&dest, js).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
        entries.push(rel_js_str);
    }

    // Generated lookup table: served-path -> embedded module source. Paths use
    // forward slashes and no leading slash (e.g. "state.js", "types/api.js").
    let mut gen = String::from("// @generated by build.rs. Do not edit.\n");
    gen.push_str("pub static MODULES: &[(&str, &str)] = &[\n");
    for e in &entries {
        gen.push_str(&format!(
            "    ({e:?}, include_str!(concat!(env!(\"OUT_DIR\"), \"/web/{e}\"))),\n"
        ));
    }
    gen.push_str("];\n");
    fs::write(out_dir.join("web_modules.rs"), gen).unwrap();
}

fn concatenate_styles(styles_dir: &Path) -> String {
    let mut files = fs::read_dir(styles_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", styles_dir.display()))
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "css"))
        .collect::<Vec<_>>();
    files.sort();
    assert!(
        !files.is_empty(),
        "no CSS files found under {}",
        styles_dir.display()
    );
    let mut output = String::new();
    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        output.push_str(
            &fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display())),
        );
    }
    output
}

fn ordered_themes(themes: &Value) -> Vec<(&str, &Map<String, Value>)> {
    let mut ordered = themes
        .as_object()
        .unwrap_or_else(|| panic!("web/themes.json must contain an object"))
        .iter()
        .map(|(id, value)| {
            let theme = value
                .as_object()
                .unwrap_or_else(|| panic!("theme {id:?} must be an object"));
            (id.as_str(), theme)
        })
        .collect::<Vec<_>>();
    ordered.sort_by_key(|(id, theme)| {
        theme
            .get("ui")
            .and_then(|ui| ui.get("order"))
            .and_then(Value::as_u64)
            .unwrap_or_else(|| panic!("theme {id:?} ui.order must be a non-negative integer"))
    });
    ordered
}

fn theme_string<'a>(theme: &'a Map<String, Value>, id: &str, path: &[&str]) -> &'a str {
    let mut value = theme
        .get(path[0])
        .unwrap_or_else(|| panic!("theme {id:?} is missing {}", path.join(".")));
    for key in &path[1..] {
        value = value
            .get(*key)
            .unwrap_or_else(|| panic!("theme {id:?} is missing {}", path.join(".")));
    }
    value
        .as_str()
        .unwrap_or_else(|| panic!("theme {id:?} {} must be a string", path.join(".")))
}

fn theme_number(theme: &Map<String, Value>, id: &str, path: &[&str]) -> String {
    let mut value = theme
        .get(path[0])
        .unwrap_or_else(|| panic!("theme {id:?} is missing {}", path.join(".")));
    for key in &path[1..] {
        value = value
            .get(*key)
            .unwrap_or_else(|| panic!("theme {id:?} is missing {}", path.join(".")));
    }
    if !value.is_number() {
        panic!("theme {id:?} {} must be a number", path.join("."));
    }
    value.to_string()
}

fn optional_theme_string<'a>(theme: &'a Map<String, Value>, path: &[&str]) -> Option<&'a str> {
    let mut value = theme.get(path[0])?;
    for key in &path[1..] {
        value = value.get(*key)?;
    }
    value.as_str()
}

fn validate_themes(themes: &Value) {
    let object = themes
        .as_object()
        .unwrap_or_else(|| panic!("web/themes.json must contain an object"));
    assert!(!object.is_empty(), "web/themes.json must define a theme");
    let mut order = Vec::new();
    for (id, value) in object {
        let theme = value
            .as_object()
            .unwrap_or_else(|| panic!("theme {id:?} must be an object"));
        for path in [
            &["name"][..],
            &["type"],
            &["color", "paper"],
            &["color", "paper2"],
            &["color", "ink"],
            &["color", "inkDim"],
            &["color", "inkFaint"],
            &["color", "accent"],
            &["color", "accent2"],
            &["color", "gold"],
            &["color", "edge"],
            &["color", "err"],
            &["color", "markBg"],
            &["color", "markFg"],
            &["color", "markCur"],
            &["color", "markCurFg"],
            &["acrylic", "tint"],
            &["background", "mode"],
            &["background", "solid"],
            &["ui", "activeLine"],
            &["ui", "edit"],
            &["ui", "foregroundFaint"],
            &["ui", "syntax", "string"],
            &["ui", "syntax", "number"],
            &["ui", "syntax", "literal"],
            &["ui", "syntax", "function"],
            &["ui", "syntax", "link"],
        ] {
            theme_string(theme, id, path);
        }
        theme_number(theme, id, &["radius"]);
        theme_number(theme, id, &["acrylic", "blur"]);
        theme_number(theme, id, &["illustration"]);
        order.push(
            theme
                .get("ui")
                .and_then(|ui| ui.get("order"))
                .and_then(Value::as_u64)
                .unwrap_or_else(|| panic!("theme {id:?} ui.order must be a non-negative integer")),
        );
    }
    order.sort_unstable();
    assert_eq!(
        order,
        (0..object.len() as u64).collect::<Vec<_>>(),
        "theme ui.order values must be unique and contiguous from zero"
    );
}

fn generate_theme_module(themes: &Value) -> String {
    let mut presets = Map::new();
    let mut builtins = Vec::new();
    for (id, theme) in ordered_themes(themes) {
        let mut preset = theme.clone();
        let ui = preset
            .remove("ui")
            .and_then(|value| value.as_object().cloned());
        let name = preset.get("name").cloned().unwrap();
        presets.insert(id.to_string(), Value::Object(preset));
        builtins.push(json!({
            "id": id,
            "name": name,
            "labelKey": ui.as_ref().and_then(|value| value.get("labelKey")).cloned(),
        }));
    }
    format!(
        "// @generated from web/themes.json by build.rs. Do not edit.\n\
         export const THEME_PRESETS = {};\n\
         export const BUILTIN_THEMES = {};\n",
        serde_json::to_string(&Value::Object(presets)).unwrap(),
        serde_json::to_string(&builtins).unwrap(),
    )
}

fn generate_desk(theme: &Map<String, Value>, id: &str) -> String {
    if theme_string(theme, id, &["background", "mode"]) == "solid" {
        return theme_string(theme, id, &["background", "solid"]).to_string();
    }
    let blobs = theme
        .get("watercolor")
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("theme {id:?} watercolor must be an array"));
    let mut layers = Vec::new();
    for blob in blobs {
        let blob = blob
            .as_object()
            .unwrap_or_else(|| panic!("theme {id:?} watercolor entries must be objects"));
        let get = |key| {
            blob.get(key)
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("theme {id:?} watercolor.{key} must be a string"))
        };
        layers.push(format!(
            "radial-gradient({} {} at {} {}, {}, transparent 60%)",
            get("rx"),
            get("ry"),
            get("x"),
            get("y"),
            get("color")
        ));
    }
    layers.push(theme_string(theme, id, &["color", "paper"]).to_string());
    layers.join(",\n    ")
}

fn generate_themes_css(themes: &Value) -> String {
    let mut css = String::from("/* @generated from web/themes.json by build.rs. Do not edit. */\n");
    for (id, theme) in ordered_themes(themes) {
        if id == "iris-light" {
            css.push_str(":root,\n");
        }
        css.push_str(&format!("html[data-theme={id:?}] {{\n"));
        let variables = [
            ("--bg", &["color", "paper"][..]),
            ("--bg-elevated", &["color", "paper2"]),
            ("--bg-toolbar", &["acrylic", "tint"]),
            ("--bg-active-line", &["ui", "activeLine"]),
            ("--gutter-bg", &["color", "paper"]),
            ("--edit-bg", &["ui", "edit"]),
            ("--fg", &["color", "ink"]),
            ("--fg-dim", &["color", "inkDim"]),
            ("--fg-faint", &["ui", "foregroundFaint"]),
            ("--border", &["color", "edge"]),
            ("--accent", &["color", "accent"]),
            ("--accent-bright", &["color", "accent2"]),
            ("--status", &["acrylic", "tint"]),
            ("--gutter-fg", &["color", "inkFaint"]),
            ("--mark-bg", &["color", "markBg"]),
            ("--mark-fg", &["color", "markFg"]),
            ("--mark-active-bg", &["color", "markCur"]),
            ("--mark-active-fg", &["color", "markCurFg"]),
            ("--danger", &["color", "err"]),
            ("--gold", &["color", "gold"]),
            ("--syn-string", &["ui", "syntax", "string"]),
            ("--syn-number", &["ui", "syntax", "number"]),
            ("--syn-literal", &["ui", "syntax", "literal"]),
            ("--syn-function", &["ui", "syntax", "function"]),
            ("--syn-link", &["ui", "syntax", "link"]),
        ];
        for (variable, path) in variables {
            css.push_str(&format!(
                "  {variable}: {};\n",
                theme_string(theme, id, path)
            ));
        }
        let status_foreground = optional_theme_string(theme, &["ui", "statusForeground"])
            .unwrap_or_else(|| theme_string(theme, id, &["color", "inkDim"]));
        css.push_str(&format!("  --status-fg: {status_foreground};\n"));
        let hover = optional_theme_string(theme, &["ui", "hover"])
            .unwrap_or("color-mix(in srgb, var(--accent) 10%, transparent)");
        let focus = optional_theme_string(theme, &["ui", "focusRing"])
            .unwrap_or_else(|| theme_string(theme, id, &["color", "accent2"]));
        css.push_str(&format!("  --hover: {hover};\n"));
        css.push_str(&format!("  --focus-ring: {focus};\n"));
        css.push_str(&format!(
            "  --radius: {}px;\n  --acrylic-blur: {}px;\n  --illus: {};\n",
            theme_number(theme, id, &["radius"]),
            theme_number(theme, id, &["acrylic", "blur"]),
            theme_number(theme, id, &["illustration"]),
        ));
        css.push_str(&format!("  --desk:\n    {};\n", generate_desk(theme, id)));
        css.push_str("}\n\n");
    }
    css
}

/// Embed the version fields that SignPath validates before accepting a Windows
/// executable. `winres` derives FileVersion and ProductVersion from the Cargo
/// package version; the remaining strings live in Cargo.toml so they are easy
/// to audit alongside the package metadata.
fn compile_windows_resources() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    winres::WindowsResource::new()
        .compile()
        .expect("compile Windows version resources");
}

fn collect_ts(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for entry in rd {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect_ts(&path, out);
        } else if path.extension().is_some_and(|e| e == "ts")
            // Declaration files are type-only: no runtime output to emit.
            && !path.to_string_lossy().ends_with(".d.ts")
        {
            out.push(path);
        }
    }
}

/// Parse a TypeScript module and emit the type-stripped ES-module JavaScript.
/// Default `TransformOptions` (no `env` target) means: strip TS types only —
/// no ESM→CJS lowering, no syntax down-levelling.
fn transform_ts(path: &Path, source: &str) -> String {
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(path).unwrap();
    let parser_ret = Parser::new(&allocator, source, source_type).parse();
    assert!(
        !parser_ret.panicked,
        "oxc failed to parse {}: {:?}",
        path.display(),
        parser_ret.diagnostics
    );
    // oxc recovers from many syntax errors without panicking and would emit
    // best-effort JS; tsc only gates CI, so recoverable parse errors must
    // fail the cargo build here or broken modules ship inside the binary.
    assert!(
        parser_ret.diagnostics.is_empty(),
        "TypeScript syntax errors in {}: {:?}",
        path.display(),
        parser_ret.diagnostics
    );
    let mut program = parser_ret.program;
    let scoping = SemanticBuilder::new()
        .with_enum_eval(true)
        .build(&program)
        .semantic
        .into_scoping();
    let options = TransformOptions::default();
    Transformer::new(&allocator, path, &options).build_with_scoping(scoping, &mut program);
    Codegen::new().build(&program).code
}

/// Reject a malformed `AYAME_UPDATE_PUBKEY` while the build is still running.
///
/// `cli::update` parses this key the first time an update is checked, so a typo
/// in a release variable would otherwise ship a binary that fails at the moment
/// a user tries to update. Failing here turns that into a failed build (#191).
fn check_update_pubkey() {
    let Some(key) = std::env::var_os("AYAME_UPDATE_PUBKEY") else {
        return; // unset: an unsigned build, which is a supported configuration
    };
    let key = key.to_string_lossy();
    let key = key.trim();
    if key.is_empty() {
        return;
    }
    let looks_like_a_key = key.len() == 64 && key.bytes().all(|b| b.is_ascii_hexdigit());
    assert!(
        looks_like_a_key,
        "AYAME_UPDATE_PUBKEY must be 64 hex characters (a 32-byte Ed25519 public \
         key), got {} characters. Generate one with `cargo xtask keygen`.",
        key.len()
    );
}
