//! Build step: type-strip the TypeScript front-end.
//!
//! The editor UI lives in `web/src/*.ts`. There is no Node toolchain in the
//! shipped build — instead this script parses each module with the oxc
//! toolchain (a Rust crate), strips the TypeScript type annotations, and writes
//! plain ES modules to `$OUT_DIR/web/`. A generated `web_modules.rs` table maps
//! each served path (`state.js`, `main.js`, …) to its embedded source; the
//! server includes that table (see `src/serve/assets.rs`) and serves the
//! modules under `/src/<name>.js`. The browser loads them as native ES modules,
//! so no bundler/minifier is involved — the transform is type-strip only and
//! keeps the `import`/`export` graph intact.
//!
//! `tsc` (the type checker) is a CI-only gate; it never runs here or in a
//! release build.

use std::fs;
use std::path::{Path, PathBuf};

use oxc_allocator::Allocator;
use oxc_codegen::Codegen;
use oxc_parser::Parser;
use oxc_semantic::SemanticBuilder;
use oxc_span::SourceType;
use oxc_transformer::{TransformOptions, Transformer};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest.join("web/src");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let web_out = out_dir.join("web");

    // Rebuild whenever a source module (or this script) changes. The directory
    // watch catches added/removed files; per-file watches catch edits.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=web/src");

    let mut ts_files = Vec::new();
    collect_ts(&src_dir, &mut ts_files);
    ts_files.sort();
    assert!(!ts_files.is_empty(), "no .ts modules found under {}", src_dir.display());

    let mut entries: Vec<String> = Vec::new();
    for path in &ts_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path.strip_prefix(&src_dir).unwrap();
        let rel_js = rel.with_extension("js");
        let rel_js_str = rel_js.to_string_lossy().replace('\\', "/");
        let source =
            fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let js = transform_ts(path, &source);
        let dest = web_out.join(&rel_js);
        fs::create_dir_all(dest.parent().unwrap()).unwrap();
        fs::write(&dest, js).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
        entries.push(rel_js_str);
    }

    // Generated lookup table: served-path -> embedded module source. Paths use
    // forward slashes and no leading slash (e.g. "state.js", "types/api.js").
    let mut gen = String::from("// @generated by build.rs. Do not edit.\n");
    gen.push_str("pub static MODULES: &[(&str, &str)] = &[\n");
    for e in &entries {
        gen.push_str(&format!(
            "    ({e:?}, include_str!(concat!(env!(\"OUT_DIR\"), \"/web/{e}\"))),\n"
        ));
    }
    gen.push_str("];\n");
    fs::write(out_dir.join("web_modules.rs"), gen).unwrap();
}

fn collect_ts(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for entry in rd {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect_ts(&path, out);
        } else if path.extension().is_some_and(|e| e == "ts") {
            out.push(path);
        }
    }
}

/// Parse a TypeScript module and emit the type-stripped ES-module JavaScript.
/// Default `TransformOptions` (no `env` target) means: strip TS types only —
/// no ESM→CJS lowering, no syntax down-levelling.
fn transform_ts(path: &Path, source: &str) -> String {
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(path).unwrap();
    let parser_ret = Parser::new(&allocator, source, source_type).parse();
    assert!(
        !parser_ret.panicked,
        "oxc failed to parse {}: {:?}",
        path.display(),
        parser_ret.diagnostics
    );
    let mut program = parser_ret.program;
    let scoping = SemanticBuilder::new()
        .with_enum_eval(true)
        .build(&program)
        .semantic
        .into_scoping();
    let options = TransformOptions::default();
    Transformer::new(&allocator, path, &options).build_with_scoping(scoping, &mut program);
    Codegen::new().build(&program).code
}
