[package]
name = "ayame-core"
description = "Memory-mapped, sparsely-indexed engine for editing extremely large text files."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
[dependencies]
memmap2.workspace = true
memchr.workspace = true
encoding_rs.workspace = true
chardetng.workspace = true
regex.workspace = true
rayon.workspace = true
thiserror.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
unicode-normalization.workspace = true
csv-core = "0.1"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
