// @generated by typeship. Do not edit.

export type Encoding = "utf8" | "shift-jis" | "euc-jp" | "ascii" | "iso-2022-jp" | "utf16-le" | "utf16-be";

export type Eol = "lf" | "crlf" | "cr" | "mixed" | "none";

export type EditLine = { number: bigint, text: string, edited: boolean, inserted: boolean, original_line: bigint | null,
/**
 * True when `text` shows only the first [`Document::MAX_VIEW_LINE_BYTES`]
 * of a longer original line (#201). Such a line is display-only: splicing
 * edits into it are refused (they would rebuild the line from truncated
 * text), and exports must not persist its text.
 */
truncated: boolean, };

export type MarkerKind = "bookmark" | "search-rule" | "change-saved" | "change-unsaved" | "change-deleted";

export type LineMarker = { kind: MarkerKind, line: bigint, };

export type SearchHit = { line: bigint,
/**
 * 0-based character column (decoded), not byte column.
 */
column: bigint, byte: bigint, byte_len: bigint, };

export type GrepHit = { path: string,
/**
 * 0-based line number (the UI shows `line + 1`).
 */
line: bigint,
/**
 * 0-based decoded character column.
 */
col: bigint,
/**
 * The matched line's text (decoded, terminator stripped, length-capped).
 */
text: string, };

export type OpenRequest = { path: string, };

export type OpenResponse = {
/**
 * Whether a file is currently open. When false, every file field is
 * absent and the front-end shows its open/welcome screen.
 */
open: boolean, path?: string, bytes?: bigint, lines?: bigint, encoding?: Encoding, eol?: Eol, bom_bytes?: bigint, stride?: bigint, checkpoints?: number, index_bytes?: number, index_ms?: bigint, from_cache?: boolean, view_lines: bigint, dirty: boolean, revision: bigint, inserted_lines: bigint, replaced_lines: bigint, deleted_lines: bigint, can_undo: boolean, can_redo: boolean,
/**
 * Present when the active document's crash log holds `n` unsaved edit
 * transactions from a previous process, waiting for a restore/discard
 * decision via `POST /api/edit/recover`.
 */
recoverable?: number,
/**
 * One-shot: crash logging failed and was disabled for this session (the
 * front-end shows it once; editing itself is unaffected).
 */
wal_error?: string, };

export type StatResponse = {
/**
 * Whether a file is currently open. When false, every file field is
 * absent and the front-end shows its open/welcome screen.
 */
open: boolean, path?: string, bytes?: bigint, lines?: bigint, encoding?: Encoding, eol?: Eol, bom_bytes?: bigint, stride?: bigint, checkpoints?: number, index_bytes?: number, index_ms?: bigint, from_cache?: boolean, view_lines: bigint, dirty: boolean, revision: bigint, inserted_lines: bigint, replaced_lines: bigint, deleted_lines: bigint, can_undo: boolean, can_redo: boolean,
/**
 * Present when the active document's crash log holds `n` unsaved edit
 * transactions from a previous process, waiting for a restore/discard
 * decision via `POST /api/edit/recover`.
 */
recoverable?: number,
/**
 * One-shot: crash logging failed and was disabled for this session (the
 * front-end shows it once; editing itself is unaffected).
 */
wal_error?: string, };

export type TailPollResponse = {
/**
 * Whether a file is open at all.
 */
open: boolean,
/**
 * New bytes were appended and the line index was extended in place.
 */
grew: boolean,
/**
 * The file shrank or was replaced externally — the client should reopen.
 */
changed: boolean,
/**
 * Growth was seen but NOT followed because the session has pending edits.
 */
pending_edits: boolean, lines: bigint, bytes: bigint, };

export type TabIdRequest = { id: bigint, };

export type TabReorderRequest = { id: bigint, before_id: bigint | null, };

export type BrowseEntry = { name: string, path: string, is_dir: boolean, size: bigint, };

export type BrowseResponse = { dir: string, parent: string | null, entries: Array<BrowseEntry>, };

export type LinesResponse = { start: bigint, total: bigint, lines: Array<EditLine>, markers: Array<LineMarker>, };

export type FindResponse = { hit: SearchHit | null, };

export type SearchResponse = { hits: Array<SearchHit>, truncated: boolean, };

export type GrepResponse = { hits: Array<GrepHit>, truncated: boolean, files_scanned: bigint, files_truncated: boolean, };

export type LineByteResponse = { byte: bigint | null, };

export type ReplaceRangeRequest = { l0: bigint, c0: number, l1: bigint, c1: number, text: string, };

export type ReplaceRectRequest = { l0: bigint, l1: bigint, c0: number, c1: number, text: string, };

export type CaretPosition = { line: bigint, col: number, };

export type EditSaveRequest = { path: string | null, overwrite: boolean,
/**
 * 名前を付けて保存 semantics: after a successful save the ACTIVE TAB shows
 * the saved file (instead of leaving the tab on the old document and
 * opening the saved copy as a second tab).
 */
switch_to_saved: boolean,
/**
 * 変換して保存: target 文字コード (e.g. "shift_jis"). When either this or
 * `eol` is set the whole file is re-encoded, so the save runs as a
 * rewrite-then-reload rather than the fast incremental path.
 */
encoding: string | null,
/**
 * 変換して保存: target 改行コード ("lf" / "crlf" / "cr").
 */
eol: string | null,
/**
 * 変換して保存: whether a UTF-8 target file gets a leading BOM. Only
 * meaningful when the target 文字コード is UTF-8 (ignored otherwise). When
 * omitted the file's current BOM state is preserved.
 */
bom: boolean | null,
/**
 * Overwrite the open file even though it changed outside the editor since
 * it was opened. Without this a save onto a file somebody else has
 * written is refused with `disk_changed`, and the client asks the user
 * whether to reload or overwrite (#163).
 */
force: boolean, };

export type EditSaveResponse = {
/**
 * UI-facing path (verbatim prefix stripped) — see [`workspace::display_path`].
 */
path: string, bytes: bigint, lines: bigint, switched: boolean, };

export type RecoverRequest = { discard: boolean, };

export type ReopenRequest = { encoding: string, };

export type MarkerToggleRequest = { kind: string, line: bigint, };

export type MarkerBulkRequest = { kind: string, lines: Array<bigint>, };

export type MarkerBulkResponse = { kind: string, added: bigint, count: bigint, limit: bigint, limit_reached: boolean, };

export type MarkerClearRequest = { kind: string, };

export type MarkerSaveRequest = { kind: string, path: string, overwrite: boolean, };

export type MarkerSaveResponse = { path: string, lines: bigint, bytes: bigint, };

export type MarkerMutationResponse = { kind: string, line: bigint, marked: boolean, count: bigint, limit: bigint, };

export type MarkerListQuery = { kind: string, start: bigint, limit: number, };

export type MarkerListResponse = { kind: string, total: bigint, lines: Array<bigint>, truncated: boolean, };

export type MarkerNavigateQuery = { kind: string, from: bigint, direction: string, wrap: boolean, };

export type MarkerNavigateResponse = { kind: string, line: bigint | null, count: bigint, wrapped: boolean, };

export type MarkerPreview = { line: bigint, text: string, truncated: boolean, };

export type MarkerPreviewResponse = { kind: string, total: bigint, entries: Array<MarkerPreview>, truncated: boolean, };

export type ChangeMarkerOverview = { count: bigint, histogram: Array<number>, };

export type ChangeHistoryResponse = { revision: bigint, total_lines: bigint, saved: ChangeMarkerOverview, unsaved: ChangeMarkerOverview, deleted: ChangeMarkerOverview, limit_reached: boolean, };

export type SelectionSaveRequest = { path: string, overwrite: boolean, rect: boolean, l0: bigint, c0: number, l1: bigint, c1: number, };

export type SelectionSaveResponse = { path: string, lines: bigint, bytes: bigint, };

export type ArtifactOpStatus = { id: string, kind: string, processed_lines: bigint, total_lines: bigint, percent: number, done: boolean, canceled: boolean, message: string | null, };

export type OperationCancelRequest = { id: string, };

export type ArtifactResponse = {
/**
 * UI-facing path (verbatim prefix stripped) — see [`workspace::display_path`].
 */
path: string, bytes: bigint, lines: bigint, };

export type SortSaveRequest = { op_id: string | null, path: string | null,
/**
 * Sort the open file onto itself (the `path` field is ignored): the sort
 * output atomically replaces the file, the document reloads, and the
 * (already incorporated) edit overlay is cleared.
 */
in_place: boolean, key: number | null, keys: Array<number> | null, numeric: boolean, reverse: boolean, delim: string | null, csv: boolean, };

export type ReplaceSaveRequest = { op_id: string | null, path: string | null, find: string, replacement: string, regex: boolean, ci: boolean, jobs: number | null, chunk_lines: bigint | null, };

export type CaseSaveRequest = { op_id: string | null, path: string | null, mode: string, jobs: number | null, chunk_lines: bigint | null, };

export type SplitSaveRequest = { op_id: string | null,
/**
 * Lines per output part (must be >= 1).
 */
lines: bigint,
/**
 * Output directory; null/absent = the source file's directory.
 */
dir: string | null, };

export type GrepRequest = { query: string,
/**
 * Root directory to search; null/absent = the open file's directory.
 */
dir: string | null,
/**
 * Comma/space separated filename globs (`*.rs, *.toml`); empty = every file.
 */
glob: string | null, regex: boolean, ci: boolean, word: boolean, max: number, };

export type GrepSaveRequest = { op_id: string | null,
/**
 * Output file; null/absent = a `.grep` suffixed sibling default.
 */
path: string | null, query: string, regex: boolean, ci: boolean, word: boolean,
/**
 * Replace an existing output file (the OS save dialog already asked).
 */
overwrite: boolean, jobs: number | null, chunk_lines: bigint | null, };

export type AnalysisRuleConfig = { id: string, name: string, pattern: string, regex: boolean, case_sensitive: boolean, whole_word: boolean, color: string, enabled: boolean, };

export type AnalysisProfile = { id: string, name: string, file_glob: string | null, rules: Array<AnalysisRuleConfig>, };

export type AnalysisStartRequest = { profile: AnalysisProfile, max_hits_per_rule: number | null, };

export type AnalysisCancelRequest = { id: string, };

export type AnalysisRuleStatus = { id: string, name: string, color: string, enabled: boolean, count: bigint, stored_hits: number, truncated: boolean, histogram: Array<bigint>, };

export type AnalysisStatus = { id: string, profile_id: string, phase: string, processed_bytes: bigint, processed_lines: bigint, total_bytes: bigint, total_lines: bigint, percent: number, histogram_bin_width: bigint, tail_pending: boolean, message: string | null, rules: Array<AnalysisRuleStatus>, };

export type AnalysisHit = { line: bigint, column: bigint, byte: bigint, byte_len: bigint, text: string, text_truncated: boolean, };

export type AnalysisNavigateResponse = { rule: string, hit: AnalysisHit | null, wrapped: boolean, };

export type AnalysisHitsResponse = { rule: string, total_count: bigint, stored_hits: number, truncated: boolean, start: number, hits: Array<AnalysisHit>, };

export type SessionState = { paths: Array<string>, active_path: string | null, };

export type SyntaxMapping = { glob: string, scheme: string, };

export type SyntaxOverride = { path: string, scheme: string, };

export type UiState = { recent_files: Array<string>, search_history: Array<string>,
/**
 * Replacement strings the user has committed, newest first — the find
 * field's history had no counterpart for the replace field (#173).
 * `#[serde(default)]` so a stored state written before this field is
 * still readable.
 */
replace_history: Array<string>, session: SessionState, analysis_profiles: Array<AnalysisProfile>, active_analysis_profile: string | null,
/**
 * Distinguishes an intentional empty favorite/mapping list from a state
 * written before syntax preferences existed (#244).
 */
syntax_configured: boolean, syntax_favorites: Array<string>, syntax_mappings: Array<SyntaxMapping>, syntax_overrides: Array<SyntaxOverride>, };

export type TabInfo = { id: bigint, name: string, path: string, dirty: boolean, active: boolean, };

export type TabsResponse = { tabs: Array<TabInfo>, };

export type DiskCheckResponse = {
/**
 * Whether a file is open at all; `changed` is meaningless when false.
 */
open: boolean,
/**
 * The file on disk is no longer the one this session last read or wrote.
 */
changed: boolean, };
