// @generated by typeship. Do not edit.

export type OpenRequest = { path: string, };

export type BrowseEntry = { name: string, path: string, is_dir: boolean, size: bigint, };

export type BrowseResponse = { dir: string, parent: string | null, entries: Array<BrowseEntry>, };

export type ReplaceRangeRequest = { l0: bigint, c0: number, l1: bigint, c1: number, text: string, };

export type CaretPosition = { line: bigint, col: number, };

export type RecoverRequest = { discard: boolean, };

export type SelectionSaveRequest = { path: string, overwrite: boolean, rect: boolean, l0: bigint, c0: number, l1: bigint, c1: number, };

export type SelectionSaveResponse = { path: string, lines: bigint, bytes: bigint, };

export type ArtifactResponse = { 
/**
 * UI-facing path (verbatim prefix stripped) — see [`workspace::display_path`].
 */
path: string, bytes: bigint, lines: bigint, };

export type SortSaveRequest = { path: string | null, 
/**
 * Sort the open file onto itself (the `path` field is ignored): the sort
 * output atomically replaces the file, the document reloads, and the
 * (already incorporated) edit overlay is cleared.
 */
in_place: boolean, key: number | null, numeric: boolean, reverse: boolean, delim: string | null, };

export type ReplaceSaveRequest = { path: string | null, find: string, replacement: string, regex: boolean, ci: boolean, jobs: number | null, chunk_lines: bigint | null, };

export type CaseSaveRequest = { path: string | null, mode: string, };
