use axum::extract::Path;
use axum::http::{header, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};

const INDEX_HTML: &str = include_str!("../../web/index.html");
const STYLE_CSS: &str = include_str!("../../web/style.css");
const FAVICON_SVG: &str = include_str!("../../web/favicon.svg");
const AYAME_LOGO_SVG: &str = include_str!("../../web/ayame-logo.svg");
const IRIS_WATERCOLOR: &[u8] = include_bytes!("../../web/iris-watercolor.png");

// Generated by build.rs: `MODULES: &[(&str, &str)]` maps each served path
// ("main.js", "state.js", "types/api.js", …) to its type-stripped module source
// (web/src/*.ts → JS via oxc). Served under `/src/<path>`.
include!(concat!(env!("OUT_DIR"), "/web_modules.rs"));

const CONTENT_SECURITY_POLICY: &str = "default-src 'self'; base-uri 'none'; object-src 'none'; \
    frame-ancestors 'none'; form-action 'none'; script-src 'self'; \
    style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'";

pub(super) async fn index() -> Response {
    asset("text/html; charset=utf-8", INDEX_HTML)
}

/// Serve a transformed ES module from the embedded table. The router mounts
/// this at `/src/{*path}`; the browser loads `/src/main.js` and follows the
/// relative `import` graph from there.
pub(super) async fn src_module(Path(path): Path<String>) -> Response {
    match MODULES.iter().find(|(name, _)| *name == path.as_str()) {
        Some((_, body)) => asset("application/javascript; charset=utf-8", body),
        None => secure((StatusCode::NOT_FOUND, "not found").into_response()),
    }
}

pub(super) async fn style_css() -> Response {
    asset("text/css; charset=utf-8", STYLE_CSS)
}

pub(super) async fn favicon_svg() -> Response {
    asset("image/svg+xml; charset=utf-8", FAVICON_SVG)
}

pub(super) async fn ayame_logo_svg() -> Response {
    asset("image/svg+xml; charset=utf-8", AYAME_LOGO_SVG)
}

pub(super) async fn iris_watercolor_png() -> Response {
    asset_bytes("image/png", IRIS_WATERCOLOR)
}

fn asset(content_type: &'static str, body: &'static str) -> Response {
    secure(([(header::CONTENT_TYPE, content_type)], body).into_response())
}

fn asset_bytes(content_type: &'static str, body: &'static [u8]) -> Response {
    secure(([(header::CONTENT_TYPE, content_type)], body).into_response())
}

fn secure(mut response: Response) -> Response {
    let headers = response.headers_mut();
    headers.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(CONTENT_SECURITY_POLICY),
    );
    headers.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    headers.insert(header::X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
    headers.insert(
        header::REFERRER_POLICY,
        HeaderValue::from_static("no-referrer"),
    );
    response
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_security_headers(response: &Response) {
        let headers = response.headers();
        assert_eq!(
            headers.get(header::CONTENT_SECURITY_POLICY).unwrap(),
            CONTENT_SECURITY_POLICY
        );
        assert_eq!(
            headers.get(header::X_CONTENT_TYPE_OPTIONS).unwrap(),
            "nosniff"
        );
        assert_eq!(headers.get(header::X_FRAME_OPTIONS).unwrap(), "DENY");
        assert_eq!(headers.get(header::REFERRER_POLICY).unwrap(), "no-referrer");
    }

    #[tokio::test]
    async fn every_ui_asset_is_hardened() {
        for response in [
            index().await,
            style_css().await,
            favicon_svg().await,
            ayame_logo_svg().await,
            iris_watercolor_png().await,
            src_module(Path("missing.js".to_string())).await,
        ] {
            assert_security_headers(&response);
        }
    }
}
