use axum::extract::Path;
use axum::http::{header, StatusCode};
use axum::response::{Html, IntoResponse, Response};

const INDEX_HTML: &str = include_str!("../../web/index.html");
const STYLE_CSS: &str = include_str!(concat!(env!("OUT_DIR"), "/web/style.css"));
const THEMES_CSS: &str = include_str!(concat!(env!("OUT_DIR"), "/web/themes.css"));
const FAVICON_SVG: &str = include_str!("../../web/favicon.svg");
const AYAME_LOGO_SVG: &str = include_str!("../../web/ayame-logo.svg");
const IRIS_WATERCOLOR: &[u8] = include_bytes!("../../web/iris-watercolor.png");

// Generated by build.rs: `MODULES: &[(&str, &str)]` maps each served path
// ("main.js", "state.js", "types/api.js", …) to its type-stripped module source
// (web/src/*.ts → JS via oxc). Served under `/src/<path>`.
include!(concat!(env!("OUT_DIR"), "/web_modules.rs"));

pub(super) async fn index() -> Html<&'static str> {
    Html(INDEX_HTML)
}

/// Serve a transformed ES module from the embedded table. The router mounts
/// this at `/src/{*path}`; the browser loads `/src/main.js` and follows the
/// relative `import` graph from there.
pub(super) async fn src_module(Path(path): Path<String>) -> Response {
    match MODULES.iter().find(|(name, _)| *name == path.as_str()) {
        Some((_, body)) => asset("application/javascript; charset=utf-8", body),
        None => (StatusCode::NOT_FOUND, "not found").into_response(),
    }
}

pub(super) async fn style_css() -> Response {
    asset("text/css; charset=utf-8", STYLE_CSS)
}

pub(super) async fn themes_css() -> Response {
    asset("text/css; charset=utf-8", THEMES_CSS)
}

pub(super) async fn favicon_svg() -> Response {
    asset("image/svg+xml; charset=utf-8", FAVICON_SVG)
}

pub(super) async fn ayame_logo_svg() -> Response {
    asset("image/svg+xml; charset=utf-8", AYAME_LOGO_SVG)
}

pub(super) async fn iris_watercolor_png() -> Response {
    asset_bytes("image/png", IRIS_WATERCOLOR)
}

fn asset(content_type: &'static str, body: &'static str) -> Response {
    ([(header::CONTENT_TYPE, content_type)], body).into_response()
}

fn asset_bytes(content_type: &'static str, body: &'static [u8]) -> Response {
    ([(header::CONTENT_TYPE, content_type)], body).into_response()
}

#[cfg(test)]
mod tests {
    use super::{STYLE_CSS, THEMES_CSS};

    #[test]
    fn build_concatenates_styles_in_responsibility_order() {
        let foundations = STYLE_CSS.find(":root {").unwrap();
        let chrome = STYLE_CSS.find("/* ---- menu bar").unwrap();
        let editor = STYLE_CSS.find("/* ---- main area").unwrap();
        let modals = STYLE_CSS.find("/* ---- modals").unwrap();
        assert!(foundations < chrome && chrome < editor && editor < modals);
        assert!(!STYLE_CSS.contains(".seg-control"));
        assert!(!STYLE_CSS.contains("html[data-theme="));
    }

    #[test]
    fn build_generates_every_theme_from_the_canonical_json() {
        let themes: serde_json::Value =
            serde_json::from_str(include_str!("../../web/themes.json")).unwrap();
        let themes = themes.as_object().unwrap();
        for id in themes.keys() {
            assert!(THEMES_CSS.contains(&format!("html[data-theme={id:?}]")));
        }
        for variable in ["--bg:", "--fg:", "--accent:", "--syn-string:", "--desk:"] {
            assert_eq!(THEMES_CSS.matches(variable).count(), themes.len());
        }
    }
}
